FROM ubuntu.20.04

MAINTAINER Shitalkumar.D@telelgobals.com

WORKDIR /opt/tomcat/

RUN curl -O https://downloads.apache.org/tomcat/tomcat-9/v9.0.41/bin/apache-tomcat-9.0.41.tar.gz
RUN tar xvfz apache*.tar.gz
RUN mv apache-tomcat-9.0.41/* /opt/tomcat/.
RUN apt-get update && apt-get install wget -y \
apt-get install -y openjdk-8-jdk && \
apt-get install -y ant && \
apt-get clean;

WORKDIR /opt/tomcat/webapps
RUN curl -O -L https://github.com/shitalkumar58627/tomcat-app/blob/main/SampleWebApp%20(1).war
EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
